# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

  

variables:
  solution: '**/*test/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    noCache: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --filter TestCategory=UnitTest'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build test'
  inputs:
    command: build
    projects: '**/*Test/*.csproj'
    arguments: '--runtime win-x64'
  continueOnError: true
  
- task: WhiteSource@21
  inputs:
             cwd: '$(System.DefaultWorkingDirectory)'

    

